WebApiandSignalR/Models/HubedEntity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApiandSignalR.Models
{
    public class HubedEntity<T> where T : class 
    {
        public T Entity { get; set; }
        public string ConnectionId { get; set; }
    }
}

WebApiandSignalR/Controllers/ApiControllers/Shared/ApiBaseController.cs
using System;
using System.Web.Http;
using WebApiandSignalR.DbContext.Context;
using WebApiandSignalR.DbContext.Context.Shared;
using Microsoft.AspNet.SignalR;

namespace WebApiandSignalR.Controllers.ApiControllers.Shared
{
    public abstract class ApiBaseController : ApiController
    {
        protected IUmsContext Context { get; set; }
        protected Lazy<IHubContext> HubContext { get; set; }
    }
}

WebApiandSignalR/Controllers/ApiControllers/Shared/IUmsController.cs
using System.Collections.Generic;
using WebApiandSignalR.Models;

namespace WebApiandSignalR.Controllers.ApiControllers.Shared
{
    public interface IUmsController<T> where T : class 
    {
        IEnumerable<T> Get();
        T Get(long id);
        void Post(HubedEntity<T> hubedEntity);
        void Put(HubedEntity<T> hubedEntity);
        void Delete(HubedEntity<T> hubedEntity);
    }
}

WebApiandSignalR/Controllers/ApiControllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using WebApiandSignalR.Controllers.ApiControllers.Shared;
using WebApiandSignalR.DbContext;
using WebApiandSignalR.DbContext.Context;
using WebApiandSignalR.DbContext.Context.Shared;
using WebApiandSignalR.DbContext.Shared;
using WebApiandSignalR.Hubs;
using WebApiandSignalR.Models;
using Microsoft.AspNet.SignalR;

namespace WebApiandSignalR.Controllers.ApiControllers
{
    public class StudentController : ApiBaseController, IUmsController<Student>
    {
        public StudentController()
        {
            Context = new FakeUmsContext();
            HubContext = new Lazy<IHubContext>(() => GlobalHost.ConnectionManager.GetHubContext<StudentHub>());
        }

        public IEnumerable<Student> Get()
        {
            return Context.Students.ToList();
        }

        public Student Get(long id)
        {
            return Context.Students.Find(id);
        }

        public void Post(HubedEntity<Student> hubedEntity)
        {
            Context.Students.Add(hubedEntity.Entity);
            Context.SaveChanges();

            /*Calling Hub
             * need to keep is as simple as possible
             * Here only sending inserted object to the page, which requested to Create 
             */
            HubContext.Value.Clients.Client(hubedEntity.ConnectionId).AfterCreated(hubedEntity.Entity);
        }

        public void Put(HubedEntity<Student> hubedEntity)
        {
            var student = Context.Students.Find(hubedEntity.Entity.Id);
            Context.Students.Remove(student);
            Context.Students.Attach(hubedEntity.Entity);
            Context.SaveChanges();

            /*Calling Hub*/
            HubContext.Value.Clients.Client(hubedEntity.ConnectionId).AfterUpdated(hubedEntity.Entity);
        }

        public void Delete(HubedEntity<Student> hubedEntity)
        {
            var id = hubedEntity.Entity.Id;
            var student = Context.Students.Find(id);
            Context.Students.Remove(student);
            Context.SaveChanges();

            /*Calling Hub*/
            HubContext.Value.Clients.Client(hubedEntity.ConnectionId).AfterRemoved(hubedEntity.Entity);
        }
    }
}

WebApiandSignalR/Controllers/StudentManageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace WebApiandSignalR.Controllers
{
    public class StudentManageController : Controller
    {
        //
        // GET: /StudentManage/

        public ActionResult Index()
        {
            return View("List");
        }

        public ActionResult List()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Update(long id)
        {
            return View(id);
        }
    }
}

WebApiandSignalR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <!-- Set the viewport so this responsive site displays correctly on mobile devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>@ViewBag.Title</title>

        <!-- Include CSS -->
        <link href="@Url.Content("~/content/bootstrap.min.css")" rel="stylesheet" />
        <link href="@Url.Content("~/content/toastr.min.css")" rel="stylesheet" />
        <link href="@Url.Content("~/content/qunit.css")" rel="stylesheet" />
        <link href="@Url.Content("~/content/style.css")" rel="stylesheet" />
        @RenderSection("styles", false)
    </head>
    <body>

        <!-- Site header and navigation -->
        <header class="top" role="header">
            <div class="container">
                <a href="#" class="navbar-brand pull-left">
                    BS3 TUTORIAL
                </a>
            </div>
        </header>

        <!-- Site banner -->
        <div class="banner">
            <div class="container">
                @RenderSection("banner", false)
            </div>
        </div>

        <!-- Middle content section -->
        <div class="middle">
            <div class="container">
                @RenderBody()
            </div>
        </div>

        <!-- Site footer -->
        <div class="bottom">
            <div class="container">
                <div class="col-md-4">
                    <h3><span class="glyphicon glyphicon-heart"></span> Footer section 1</h3>
                    <p>Content for the first footer section.</p>
                </div>
                <div class="col-md-4">
                    <h3><span class="glyphicon glyphicon-star"></span> Footer section 2</h3>
                    <p>Content for the second footer section.</p>
                </div>
                <div class="col-md-4">
                    <h3><span class="glyphicon glyphicon-music"></span> Footer section 3</h3>
                    <p>Content for the third footer section.</p>
                </div>
            </div>
        </div>

        <!-- Include JS -->
        <script src="@Url.Content("~/Scripts/jquery-2.1.1.js")"></script>
        <script src="@Url.Content("~/Scripts/bootstrap.js")"></script>
        <script src="@Url.Content("~/Scripts/bootbox.js")"></script>
        <script src="@Url.Content("~/Scripts/toastr.js")"></script>        
        <script src="@Url.Content("~/Scripts/amplify.js")"></script>
        <script src="@Url.Content("~/Scripts/knockout-3.2.0.js")"></script>
        <script src="@Url.Content("~/Scripts/Views/Shared/Extentions/ko.extn.js")"></script>
        <script src="@Url.Content("~/Scripts/knockout.validation.js")"></script>
        <script src="@Url.Content("~/Scripts/qunit.js")"></script>     
        <script src="@Url.Content("~/Scripts/jquery.signalR-1.1.4.js")"></script>     
        <script src="@Url.Content("~/signalr/hubs")"></script> 
        @RenderSection("scripts", false)
    </body>
</html>

WebApiandSignalR/Views/StudentManage/Create.cshtml
@{
    ViewBag.Title = "Create Student";
}

<h2>Create Student</h2>
<br/>

<div class="col-lg-2">
    <a class="btn btn-primary" href="@Url.Action("List", "StudentManage")">Go Back</a>
</div>

<div class="col-lg-8">
    <form id="frmCreateStudent" class="form-horizontal" role="#">
        <div class="form-group">
            <label class="col-sm-2 control-label">First Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control"  placeholder="First Name" data-bind="value: student.firstName" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Last Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" placeholder="LastName Name" data-bind="value: student.lastName" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Address </label>
            <div class="col-sm-10">
                <textarea class="form-control" placeholder="Address" data-bind="value: student.address"></textarea>
            </div>
        </div>
        <div class="form-group" style="display: none" data-bind="style: { display: isDirty() ? 'block' : 'none' }">
            <label class="col-sm-2"></label>
            <div class="col-sm-10 btn-toolbar">
                <a class="btn btn-success" href="#" data-bind="click: create">
                    Create
                </a>
                <a class="btn btn-info" href="#" data-bind="click: reset">
                    Reset
                </a>
            </div>
        </div>
    </form>
</div>
<div class="col-lg-2"></div>


@section scripts{
    <script data-main="@Url.Content("~/Scripts/Views/StudentManage/create.js")" src="@Url.Content("~/Scripts/require.js")"></script>
}

WebApiandSignalR/Views/StudentManage/List.cshtml
@{
    ViewBag.Title = "Student List";
}

<h2>Student List</h2>
<br/>
<br/>

<a class="btn btn-primary" href="@Url.Action("Create", "StudentManage")">Create</a>
<br/>
<br/>

<div id="divStudentList" class="table-responsive">
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Sn</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Address</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody data-bind="foreach: students">
            <tr>
                <td data-bind="text: $index() + 1"></td>
                <td data-bind="text: firstName()"></td>
                <td data-bind="text: lastName"></td>
                <td data-bind="text: address"></td>
                <td>
                    <a data-bind="click: $root.showInNewPage">Update</a>
                    <a data-bind="click: $root.confirmToRemove">Delete</a>
                </td>
            </tr>
        </tbody>
    </table>
</div>

@*<div class="table-responsive">
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Sn</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Address</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>Jamal</td>
                <td>Jamal</td>
                <td>Jamal</td>
                <td>
                    <a>Update</a>
                    <a>Delete</a>
                </td>
            </tr>
            <tr>
                <td>1</td>
                <td>Jamal</td>
                <td>Jamal</td>
                <td>Jamal</td>
                <td>
                    <a>Update</a>
                    <a>Delete</a>
                </td>
            </tr>
            <tr>
                <td>1</td>
                <td>Jamal</td>
                <td>Jamal</td>
                <td>Jamal</td>
                <td>
                    <a>Update</a>
                    <a>Delete</a>
                </td>
            </tr>
            <tr>
                <td>1</td>
                <td>Jamal</td>
                <td>Jamal</td>
                <td>Jamal</td>
                <td>
                    <a>Update</a>
                    <a>Delete</a>
                </td>
            </tr>
            <tr>
                <td>1</td>
                <td>Jamal</td>
                <td>Jamal</td>
                <td>Jamal</td>
                <td>
                    <a>Update</a>
                    <a>Delete</a>
                </td>
            </tr>
            <tr>
                <td>1</td>
                <td>Jamal</td>
                <td>Jamal</td>
                <td>Jamal</td>
                <td>
                    <a>Update</a>
                    <a>Delete</a>
                </td>
            </tr>
            <tr>
                <td>1</td>
                <td>Jamal</td>
                <td>Jamal</td>
                <td>Jamal</td>
                <td>
                    <a>Update</a>
                    <a>Delete</a>
                </td>
            </tr>            <tr>
                                 <td>1</td>
                                 <td>Jamal</td>
                                 <td>Jamal</td>
                                 <td>Jamal</td>
                                 <td>
                                     <a>Update</a>
                                     <a>Delete</a>
                                 </td>
                             </tr>
            <tr>
                <td>1</td>
                <td>Jamal</td>
                <td>Jamal</td>
                <td>Jamal</td>
                <td>
                    <a>Update</a>
                    <a>Delete</a>
                </td>
            </tr>

        </tbody>
    </table>
</div>*@

@section scripts{
    <script data-main="@Url.Content("~/Scripts/Views/StudentManage/list.js")" src="@Url.Content("~/Scripts/require.js")"></script>
}

WebApiandSignalR/Views/StudentManage/Update.cshtml
@model long

@{
    ViewBag.Title = "Update Student";
}

<h2>Update Student</h2>
<br />

<input id="txtStudentUpdateId" type="hidden" value="@(Model)" data-bind="value: student.id"/>

<div class="col-lg-2">
    <a class="btn btn-primary" href="@Url.Action("List", "StudentManage")">Go Back</a>
</div>

<div class="col-lg-8">
    <form id="frmUpdateStudent" class="form-horizontal" role="#" data-bind="style: { display: !isRemovedByOthers() ? 'block' : 'none' }">
        <div class="form-group">
            <label class="col-sm-2 control-label">First Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" placeholder="First Name" data-bind="value: student.firstName" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Last Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" placeholder="LastName Name" data-bind="value: student.lastName" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Address </label>
            <div class="col-sm-10">
                <textarea class="form-control" placeholder="Address" data-bind="value: student.address"></textarea>
            </div>
        </div>
        <div class="form-group" style="display: none" data-bind="style: { display: isDirty() ? 'block' : 'none' }">
            <label class="col-sm-2"></label>
            <div class="col-sm-10 btn-toolbar">
                <a class="btn btn-success" style="display: inline" href="#" data-bind="click: update, 
                                                                                        style: { display: !isUpdatedByOthers() ? 'inline' : 'none' }">
                    Update
                </a>
                <a class="btn btn-info" href="#" data-bind="click: reset">Reset
                </a>
            </div>
        </div>
    </form>
</div>
<div class="col-lg-2"></div>



@section scripts{
    <script data-main="@Url.Content("~/Scripts/Views/StudentManage/update.js")" src="@Url.Content("~/Scripts/require.js")"></script>
}